name: Draw ZMK Keymaps
on:
  workflow_call:
    inputs:
      keymap_patterns:
        description: 'Path specification for keymaps to be parsed'
        default: 'config/*.keymap'
        required: false
        type: string
      commit_message:
        description: 'Commit message for updated images. Ignored if `amend_commit` is `true`.'
        default: 'keymap-drawer render'
        required: false
        type: string
      amend_commit:
        description: 'Whether to amend the last commit instead of creating a new one. Make sure you understand the implications of rewriting the branch history if you use this option!'
        default: false
        required: false
        type: boolean
      output_folder:
        description: 'Output folder for SVG and YAML files'
        default: 'keymap-drawer'
        required: false
        type: string
      json_path:
        description: 'Path containing <keymap>.json physical layout description files, ignored if non-existent'
        default: 'config'
        required: false
        type: string
      destination:
        description: 'Add the output files to a commit, as artifacts or both, values: `commit`, `artifact`, `both`'
        default: 'commit'
        required: false
        type: string
      artifact_name:
        description: 'Name of the produced artifact containing SVG and YAML outputs. Ignored if `destination` is `commit`.'
        default: 'drawings'
        required: false
        type: string
      fail_on_error:
        description: 'Fail the action if an error occurs during parse/draw'
        default: false
        required: false
        type: boolean

jobs:
  draw:
    runs-on: ubuntu-latest
    outputs:
      drawings: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # So the reference to the parent commit is available when amending
          # See:
          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
          # - https://github.com/actions/checkout
          fetch-depth: ${{ (inputs.amend_commit == true && 2) || 1 }}
          submodules: recursive

      - name: Install keymap-drawer (pypi)
        run: pipx install keymap-drawer

      - name: Install keymap-drawer (git)
        run: pipx install oyaml

      - name: DRAW
        id: draw
        run: cd ./keymap_img && chmod +x ./update_keymap.sh && ./update_keymap.sh

      - name: Get last commit message
        id: last_commit_message
        if: inputs.amend_commit == true && (inputs.destination == 'commit' || inputs.destination == 'both')
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Commit updated images
        if: ( inputs.destination == 'commit' || inputs.destination == 'both' )
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '${{ inputs.output_folder }}/*.svg ${{ inputs.output_folder }}/*.yaml'
          commit_message: '${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}'
          commit_options: "${{ (inputs.amend_commit == true && '--amend --no-edit') || '' }}"
          push_options: "${{ (inputs.amend_commit == true && '--force-with-lease') || '' }}"
          skip_fetch: ${{ inputs.amend_commit == true }}

      - name: Artifact upload
        id: artifact-upload-step
        if: ( inputs.destination == 'artifact' || inputs.destination == 'both' )
        uses: actions/upload-artifact@v4
        with:
          name: '${{ inputs.artifact_name }}'
          path: |
            ${{ join(fromJSON(steps.draw.outputs.DRAWINGS), '
            ') }}
